import "server-only";
import { z } from "zod";
import type { ApiResult, CreateIssueInput } from "@/lib/contracts/v1";
import type { GroupTask, Issue } from "@/lib/domain/types";
import { issueSchema } from "@/lib/validation/issue";
import { createClient, requireServerUser } from "@/lib/supabase/server";

function failure<T>(message: string, code: "VALIDATION" | "CONFLICT" | "FORBIDDEN" | "NOT_FOUND" | "UNAVAILABLE" = "UNKNOWN" as never): ApiResult<T> { return { ok: false, error: { code, message } }; }
export function mapIssue(row: Record<string, unknown>): Issue { return { id: String(row.id), title: String(row.title), description: String(row.description), category: row.category as Issue["category"], location: String(row.location), latitude: Number(row.latitude), longitude: Number(row.longitude), observedAt: String(row.observed_at), createdAt: String(row.created_at), verificationCount: Number(row.verification_count || 0), reviewStatus: row.review_status as Issue["reviewStatus"], urgent: Boolean(row.urgent), source: row.source as Issue["source"] }; }

export async function listPublicIssues(input: { q?: string; category?: string; reviewStatus?: string; source?: string; urgent?: boolean; page?: number; pageSize?: number } = {}): Promise<ApiResult<{ items: Issue[]; page: number; pageSize: number; total: number }>> { const client = await createClient(); if (!client) return failure("Supabase is not configured.", "UNAVAILABLE"); const pageSize = Math.min(100, Math.max(1, Math.floor(input.pageSize || 20))); const page = Math.max(1, Math.floor(input.page || 1)); let query = client.from("public_issue_feed").select("*", { count: "exact" }); if (input.q?.trim()) query = query.or(`title.ilike.%${input.q.trim()}%,description.ilike.%${input.q.trim()}%,location.ilike.%${input.q.trim()}%`); if (input.category && input.category !== "all") query = query.eq("category", input.category); if (input.reviewStatus && input.reviewStatus !== "all") query = query.eq("review_status", input.reviewStatus); if (input.source && input.source !== "all") query = query.eq("source", input.source); if (input.urgent !== undefined) query = query.eq("urgent", input.urgent); const { data, error, count } = await query.order("urgent", { ascending: false }).order("created_at", { ascending: false }).range((page - 1) * pageSize, page * pageSize - 1); return error ? failure("Public issues are unavailable.", "UNAVAILABLE") : { ok: true, data: { items: (data || []).map((row) => mapIssue(row as Record<string, unknown>)), page, pageSize, total: count || 0 } }; }
export async function getPublicIssue(id: string): Promise<ApiResult<Issue>> { const client = await createClient(); if (!client) return failure("Supabase is not configured.", "UNAVAILABLE"); const { data, error } = await client.from("public_issue_feed").select("*").eq("id", id).maybeSingle(); return error ? failure("Issue is unavailable.", "UNAVAILABLE") : !data ? failure("Issue not found.", "NOT_FOUND") : { ok: true, data: mapIssue(data as Record<string, unknown>) }; }

export async function createIssueForCurrentUser(input: CreateIssueInput): Promise<ApiResult<Issue>> { const parsed = issueSchema.safeParse(input); if (!parsed.success) return failure("The report contains invalid fields.", "VALIDATION"); let user; try { user = await requireServerUser(); } catch { return failure("Authentication required.", "FORBIDDEN"); } const client = await createClient(); if (!client) return failure("Supabase is not configured.", "UNAVAILABLE"); const { data, error } = await client.from("issues").insert({ title: parsed.data.title, description: parsed.data.description, category: parsed.data.category, location: parsed.data.location, geom: `SRID=4326;POINT(${parsed.data.longitude} ${parsed.data.latitude})`, observed_at: parsed.data.observedAt, source: "citizen", reporter_id: user.id, review_status: "unverified", urgent: false }).select("id").single(); if (error || !data) return failure("The report could not be saved.", "UNAVAILABLE"); const { data: publicRow, error: readError } = await client.from("public_issue_feed").select("*").eq("id", data.id).single(); return readError || !publicRow ? failure("The report was created but could not be read back.", "UNAVAILABLE") : { ok: true, data: mapIssue(publicRow) }; }

export async function verifyIssueForCurrentUser(issueId: string): Promise<ApiResult<{ verificationCount: number }>> { const client = await createClient(); if (!client) return failure("Supabase is not configured.", "UNAVAILABLE"); let user; try { user = await requireServerUser(); } catch { return failure("Authentication required.", "FORBIDDEN"); } const { error } = await client.from("issue_verifications").insert({ issue_id: issueId, user_id: user.id, personally_observed: true }); if (error) return failure(error.code === "23505" ? "You have already verified this issue." : "Verification could not be recorded.", error.code === "23505" ? "CONFLICT" : "UNAVAILABLE"); const { count } = await client.from("issue_verifications").select("issue_id", { count: "exact", head: true }).eq("issue_id", issueId); return { ok: true, data: { verificationCount: count || 0 } }; }

export async function challengeIssueForCurrentUser(input: { issueId: string; reason: string; details?: string }): Promise<ApiResult<{ challengeId: string }>> { const parsed = z.object({ issueId: z.string().min(1), reason: z.string().trim().min(10).max(2000), details: z.string().max(4000).optional() }).safeParse(input); if (!parsed.success) return failure("A meaningful challenge reason is required.", "VALIDATION"); const client = await createClient(); if (!client) return failure("Supabase is not configured.", "UNAVAILABLE"); let user; try { user = await requireServerUser(); } catch { return failure("Authentication required.", "FORBIDDEN"); } const { data, error } = await client.from("issue_challenges").insert({ issue_id: parsed.data.issueId, actor_id: user.id, reason: parsed.data.reason, details: parsed.data.details }).select("id").single(); if (error) return failure(error.code === "23505" ? "You have already challenged this issue." : "Challenge could not be recorded.", error.code === "23505" ? "CONFLICT" : "UNAVAILABLE"); return { ok: true, data: { challengeId: String(data.id) } }; }

export async function setProjectFollowForCurrentUser(projectId: string, following: boolean): Promise<ApiResult<{ following: boolean }>> { const client = await createClient(); if (!client) return failure("Supabase is not configured.", "UNAVAILABLE"); let user; try { user = await requireServerUser(); } catch { return failure("Authentication required.", "FORBIDDEN"); } const { data: project } = await client.from("projects").select("id").eq("id", projectId).eq("is_published", true).maybeSingle(); if (!project) return failure("Published project not found.", "NOT_FOUND"); const query = following ? client.from("project_follows").upsert({ project_id: projectId, user_id: user.id }, { onConflict: "project_id,user_id" }) : client.from("project_follows").delete().eq("project_id", projectId).eq("user_id", user.id); const { error } = await query; return error ? failure("Project follow could not be updated.", "UNAVAILABLE") : { ok: true, data: { following } }; }
export async function getProjectFollowForCurrentUser(projectId: string): Promise<ApiResult<{ following: boolean }>> { const client = await createClient(); if (!client) return failure("Supabase is not configured.", "UNAVAILABLE"); let user; try { user = await requireServerUser(); } catch { return failure("Authentication required.", "FORBIDDEN"); } const { data, error } = await client.from("project_follows").select("project_id").eq("project_id", projectId).eq("user_id", user.id).maybeSingle(); return error ? failure("Follow status is unavailable.", "UNAVAILABLE") : { ok: true, data: { following: Boolean(data) } }; }

export async function confirmTaskForCurrentUser(input: { taskId: string; decision: "confirmed" | "disputed"; reason?: string }): Promise<ApiResult<GroupTask>> { if (input.decision === "disputed" && (!input.reason || input.reason.trim().length < 10)) return failure("A meaningful dispute reason is required.", "VALIDATION"); const client = await createClient(); if (!client) return failure("Supabase is not configured.", "UNAVAILABLE"); try { await requireServerUser(); } catch { return failure("Authentication required.", "FORBIDDEN"); } const { data, error } = await client.rpc("respond_to_community_task_completion", { p_task_id: input.taskId, p_decision: input.decision, p_note: input.reason || null }); if (error || !data?.length) return failure(error?.code === "23505" ? "You have already responded to this task." : error?.message || "Confirmation could not be recorded.", error?.code === "23505" ? "CONFLICT" : error?.code === "42501" ? "FORBIDDEN" : error?.code === "P0002" ? "NOT_FOUND" : error?.code === "22023" ? "CONFLICT" : "UNAVAILABLE"); const row = data[0] as Record<string, unknown>; return { ok: true, data: { id: String(row.id), issueId: String(row.issue_id), groupId: String(row.group_id), status: row.status as GroupTask["status"], updatedAt: String(row.updated_at), confirmationCount: Number(row.confirmation_count || 0) } }; }

export async function createSimulatedPledgeForCurrentUser(input: { campaignId: string; amount: number; sponsorLabel?: string }): Promise<ApiResult<{ pledgeId: string; simulated: true }>> { if (!Number.isFinite(input.amount) || input.amount <= 0) return failure("Pledge amount must be positive.", "VALIDATION"); const client = await createClient(); if (!client) return failure("Supabase is not configured.", "UNAVAILABLE"); let user; try { user = await requireServerUser(); } catch { return failure("Authentication required.", "FORBIDDEN"); } const { data: campaign } = await client.from("sponsorship_campaigns").select("id").eq("id", input.campaignId).eq("status", "active").maybeSingle(); if (!campaign) return failure("Active campaign not found.", "NOT_FOUND"); const { data, error } = await client.from("sponsorship_pledges").insert({ campaign_id: input.campaignId, sponsor_id: user.id, sponsor_label: input.sponsorLabel || null, amount: input.amount, simulated: true }).select("id").single(); return error || !data ? failure("Simulated pledge could not be recorded.", "UNAVAILABLE") : { ok: true, data: { pledgeId: String(data.id), simulated: true } }; }
