"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { neighbourhoodMockApi, setNeighbourhoodDemoActor } from "@/lib/mock-api/neighbourhood";
import type { Issue } from "@/lib/domain/types";

export function IssueDetail({ id, backHref = "/neighbourhood" }: { id: string; backHref?: string }) {
  const [issue, setIssue] = useState<Issue | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { const actor = window.localStorage.getItem("civicsync-demo-actor"); if (actor) setNeighbourhoodDemoActor(actor); neighbourhoodMockApi.getIssue(id).then((result) => { if (result.ok) setIssue(result.data); else setError(result.error.message); setLoading(false); }); }, [id]);
  async function verify() { if (!issue || busy) return; setBusy(true); const result = await neighbourhoodMockApi.verifyIssue(issue.id); setBusy(false); if (result.ok) { setIssue({ ...issue, verificationCount: result.data.verificationCount }); setMessage("Your independent observation was recorded in demo mode. This does not confirm or resolve the issue officially."); } else setMessage(result.error.message); }
  async function flag() { if (!issue || busy) return; setBusy(true); const result = await neighbourhoodMockApi.flagIssue({ issueId: issue.id, reason }); setBusy(false); if (result.ok) { setReason(""); setMessage("Your challenge was submitted for review in demo mode; it did not remove or change the report."); } else setMessage(result.error.message); }
  if (loading) return <main className="container" style={{ paddingTop: 42 }}><p className="card">Loading issue…</p></main>;
  if (error || !issue) return <main className="container" style={{ paddingTop: 42 }}><p className="card" role="alert">{error || "Issue not found."} <Link href={backHref} style={{ textDecoration: "underline" }}>Back to issue reports</Link></p></main>;
  return <main className="container" style={{ maxWidth: 820, paddingTop: 42 }}><Link href={backHref} style={{ color: "var(--green)" }}>← All issue reports</Link><div className="eyebrow" style={{ marginTop: 24 }}>{issue.urgent ? "Urgent hazard · " : ""}{issue.category.replaceAll("_", " ")}</div><h1>{issue.title}</h1><p style={{ fontSize: 18, lineHeight: 1.6 }}>{issue.description}</p><div className="card"><p><strong>Location:</strong> {issue.location}</p><p><strong>Observed:</strong> {new Date(issue.observedAt).toLocaleString()}</p><p><strong>Source:</strong> {issue.source === "citizen" ? "Resident observation" : `${issue.source} observation`}</p><p><strong>Official review:</strong> {issue.reviewStatus}. Community observations are separate and do not decide this status.</p><p><strong>Independent observations:</strong> {issue.verificationCount}</p></div><div className="card" style={{ marginTop: 16 }}><h2>Actions for residents</h2><p style={{ color: "var(--muted)" }}>Only verify if you personally observed this issue. Demo identity is stored locally and is not production authentication.</p><button className="button" onClick={verify} disabled={busy}>I observed this issue</button><div style={{ borderTop: "1px solid var(--line)", marginTop: 22, paddingTop: 12 }}><label className="label">Challenge this report<textarea className="field" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explain what may be inaccurate or misleading (at least 10 characters)." rows={3} /></label><button className="button secondary" onClick={flag} disabled={busy || reason.trim().length < 10}>Submit challenge</button></div>{message && <p role="status" style={{ color: "var(--green)" }}>{message}</p>}</div></main>;
}
