"use client";
import { useState } from "react";
import type { GroupTask } from "@/lib/domain/types";

export function TaskConfirmation({ task, onResponded }: { task: GroupTask; onResponded?: (task: GroupTask) => void }) {
  const [busy, setBusy] = useState(false); const [reason, setReason] = useState(""); const [message, setMessage] = useState("");
  async function decide(decision: "confirmed" | "disputed") { if (busy) return; setBusy(true); try { const response = await fetch(`/api/community-partners/tasks/${task.id}/confirmation`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, reason }) }); const result = await response.json() as { ok?: boolean; data?: GroupTask; error?: { message?: string } }; if (response.ok && result.ok && result.data) { onResponded?.(result.data); setMessage("Your independent community response was recorded. It does not resolve the issue officially."); } else setMessage(result.error?.message ?? "Confirmation could not be recorded."); } catch { setMessage("Confirmation could not be recorded."); } finally { setBusy(false); } }
  return <section className="card" aria-label="Community task confirmation"><div className="eyebrow">Independent community confirmation</div><p>Group completion claim: <strong>{task.status.replaceAll("_", " ")}</strong> · {task.confirmationCount} independent response{task.confirmationCount === 1 ? "" : "s"}. Responses are separate from official issue review and do not close the issue.</p>{task.status === "awaiting_confirmation" && <><label className="label">Reason if disputing (optional for confirmation)<textarea className="field" value={reason} onChange={(event) => setReason(event.target.value)} rows={3} /></label><button className="button" onClick={() => decide("confirmed")} disabled={busy}>Confirm completion</button> <button className="button secondary" onClick={() => decide("disputed")} disabled={busy || reason.trim().length < 10}>Dispute completion</button></>}{message && <p role="status" style={{ color: "var(--green)" }}>{message}</p>}</section>;
}
