import type { AdminApi } from "@/lib/contracts/v1";
import { fail, matchesText, ok, paginate } from "@/lib/mock-api/helpers";
import { applicationRows, coordinationRows, inspectionRows, issueRows, projectMatchRows, projectRows } from "@/lib/mock-api/state";

export const adminMockApi: AdminApi = {
  async listProjects(query = {}) { const rows = projectRows.filter((row) => (!query.status || query.status === "all" || row.status === query.status) && (!query.department || row.department === query.department) && (!query.ward || row.ward === query.ward) && matchesText(query.q, row.title, row.description, row.location)); return ok(paginate(rows, query)); },
  async createProject(input) { if (!input.title.trim() || !input.department.trim() || !input.location.trim()) return fail("VALIDATION", "Title, department, and location are required."); if (input.expectedEndDate < input.startDate) return fail("VALIDATION", "Expected completion must be on or after the start date."); const slug = input.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); const row = { ...input, id: `prj-mock-${Date.now()}`, slug, updatedAt: new Date().toISOString(), originalExpectedEndDate: input.expectedEndDate }; projectRows.unshift(row); return ok(row); },
  async updateProject(projectId, patch, reason) { const row = projectRows.find((item) => item.id === projectId); if (!row) return fail("NOT_FOUND", "Project not found."); if (!reason.trim()) return fail("VALIDATION", "A change reason is required."); Object.assign(row, patch, { updatedAt: new Date().toISOString() }); return ok(row); },
  async listIssues(query = {}) { const rows = issueRows.filter((row) => (!query.category || query.category === "all" || row.category === query.category) && (!query.reviewStatus || query.reviewStatus === "all" || row.reviewStatus === query.reviewStatus) && (!query.source || query.source === "all" || row.source === query.source) && (query.urgent === undefined || query.urgent === "all" || row.urgent === query.urgent) && matchesText(query.q, row.title, row.description, row.location)); return ok(paginate(rows, query)); },
  async decideIssue(input) { const row = issueRows.find((item) => item.id === input.issueId); if (!row) return fail("NOT_FOUND", "Issue not found."); if (!input.reason.trim()) return fail("VALIDATION", "A decision reason is required."); const status = { accept: "accepted", reject: "rejected", refer: "referred", more_info: "more_info", duplicate: "duplicate" } as const; row.reviewStatus = status[input.action]; row.reviewNote = input.reason; if (input.action === "duplicate") row.duplicateOf = input.canonicalIssueId; return ok({ issueId: row.id, reviewStatus: row.reviewStatus }); },
  async decideProjectMatch(issueId, projectId, decision, reason) { if (!issueRows.some((row) => row.id === issueId) || !projectRows.some((row) => row.id === projectId)) return fail("NOT_FOUND", "Issue or project not found."); if (!reason.trim()) return fail("VALIDATION", "A match decision reason is required."); const result = { issueId, projectId, decision: decision === "approve" ? "approved" as const : "rejected" as const, reason }; const old = projectMatchRows.findIndex((row) => row.issueId === issueId && row.projectId === projectId); if (old >= 0) projectMatchRows[old] = result; else projectMatchRows.push(result); return ok({ issueId, projectId, decision: result.decision }); },
  async createCoordinationCase(input) { if (!input.title.trim() || !input.reason.trim() || input.projectSlugs.length === 0) return fail("VALIDATION", "A title, reason, and at least one project are required."); const row = { id: `coord-mock-${Date.now()}`, ...input, status: "detected" as const }; coordinationRows.unshift(row); return ok(row); },
  async listCoordinationCases() { return ok(coordinationRows); },
  async decideCoordinationCase(input) { const row = coordinationRows.find((item) => item.id === input.caseId); if (!row) return fail("NOT_FOUND", "Coordination case not found."); if (!input.reason.trim()) return fail("VALIDATION", "A decision reason is required."); row.status = input.decision; row.decisionReason = input.reason; row.proposedDates = input.proposedDates; return ok(row); },
  async listRestorationInspections() { return ok(inspectionRows); },
  async listGroupApplications() { return ok(applicationRows); },
  async decideGroupApplication(input) { const row = applicationRows.find((item) => item.id === input.applicationId); if (!row) return fail("NOT_FOUND", "Application not found."); if (!input.reason.trim()) return fail("VALIDATION", "A decision reason is required."); const status = { approve: "approved", reject: "rejected", more_info: "more_info", suspend: "suspended" } as const; row.status = status[input.decision]; row.reason = input.reason; return ok(row); },
  async recordRestoration(input) { const row = inspectionRows.find((item) => item.id === input.inspectionId); if (!row) return fail("NOT_FOUND", "Inspection not found."); row.status = input.outcome; row.outcome = input.note; row.inspector = "Demo Admin"; return ok(row); },
};

