import type { CommunityPartnersApi } from "@/lib/contracts/v1";
import { fail, matchesText, ok, paginate, toPublicIssue } from "@/lib/mock-api/helpers";
import { applicationRows, campaignRows, campaignUseRows, issueRows, partnerRows, taskRows } from "@/lib/mock-api/state";

const referralRows: Array<{ id: string; issueId: string; groupId: string; reason: string; createdAt: string }> = [];

export const communityPartnersMockApi: CommunityPartnersApi = {
  async listOpportunities(query = {}) { const rows = issueRows.filter((row) => (!query.category || query.category === "all" || row.category === query.category) && (!query.reviewStatus || query.reviewStatus === "all" || row.reviewStatus === query.reviewStatus) && (!query.source || query.source === "all" || row.source === query.source) && (query.urgent === undefined || query.urgent === "all" || row.urgent === query.urgent) && matchesText(query.q, row.title, row.description, row.location)).sort((a, b) => Number(b.urgent) - Number(a.urgent) || b.verificationCount - a.verificationCount || a.createdAt.localeCompare(b.createdAt)); return ok(paginate(rows.map(toPublicIssue), query)); },
  async listMyTasks(groupId) { return ok(paginate(taskRows.filter((row) => row.groupId === groupId))); },
  async getPublicProfile(slug) { const row = partnerRows.find((item) => item.slug === slug && item.approved); return row ? ok(row) : fail("NOT_FOUND", "Approved Community Partner not found."); },
  async submitApplication(input) { if (!input.name.trim() || !input.description.trim() || !input.area.trim() || !input.contact.trim() || input.capabilities.length === 0) return fail("VALIDATION", "Name, description, contact, service area, and at least one capability are required."); const id = `application-mock-${Date.now()}`; applicationRows.push({ id, name: input.name, area: input.area, capabilities: input.capabilities, submittedAt: new Date().toISOString(), status: "pending" }); return ok({ applicationId: id, status: "pending" }); },
  async updateProfile(input) { const group = partnerRows.find((row) => row.id === input.groupId && row.approved); if (!group) return fail("FORBIDDEN", "Only an approved Community Partner profile can be edited."); if (!input.area.trim() || !input.contact.trim()) return fail("VALIDATION", "Service area and contact are required."); Object.assign(group, { description: input.description, area: input.area, contact: input.contact, capabilities: input.capabilities }); return ok(group); },
  async acceptTask(input) { const group = partnerRows.find((row) => row.id === input.groupId && row.approved); if (!group) return fail("FORBIDDEN", "Only an approved Community Partner may accept a task."); const issue = issueRows.find((row) => row.id === input.issueId); if (!issue) return fail("NOT_FOUND", "Issue not found."); if (!group.capabilities.includes(issue.category)) return fail("VALIDATION", "This issue is outside the demo partner’s listed capabilities."); if (taskRows.some((row) => row.issueId === input.issueId && row.status !== "referred" && row.status !== "disputed")) return fail("CONFLICT", "This demo issue already has an active group task."); const task = { id: `task-mock-${Date.now()}`, issueId: input.issueId, groupId: input.groupId, status: "adopted" as const, updatedAt: new Date().toISOString(), confirmationCount: 0 }; taskRows.push(task); return ok(task); },
  async referTask(input) { if (!partnerRows.some((row) => row.id === input.groupId && row.approved)) return fail("FORBIDDEN", "Only an approved Community Partner may refer work."); if (!issueRows.some((row) => row.id === input.issueId)) return fail("NOT_FOUND", "Issue not found."); if (!input.reason.trim()) return fail("VALIDATION", "A referral reason is required."); const id = `referral-mock-${Date.now()}`; referralRows.push({ id, issueId: input.issueId, groupId: input.groupId, reason: input.reason, createdAt: new Date().toISOString() }); return ok({ referralId: id }); },
  async postProgress(input) { const task = taskRows.find((row) => row.id === input.taskId); if (!task) return fail("NOT_FOUND", "Group task not found."); if (!input.note.trim()) return fail("VALIDATION", "Add a progress note."); if (task.status !== "adopted" && task.status !== "in_progress" && task.status !== "reopened") return fail("CONFLICT", "Progress can only be added to active work."); task.status = "in_progress"; task.updatedAt = new Date().toISOString(); return ok(task); },
  async submitCompletion(input) { const task = taskRows.find((row) => row.id === input.taskId); if (!task) return fail("NOT_FOUND", "Group task not found."); if (!input.note.trim() || !input.evidence) return fail("VALIDATION", "A completion note and evidence file are required."); if (task.status !== "in_progress" && task.status !== "adopted") return fail("CONFLICT", "Task is not ready for completion review."); task.status = "awaiting_confirmation"; task.completionEvidence = input.evidence.name || "demo-evidence"; task.updatedAt = new Date().toISOString(); return ok(task); },
  async createCampaign(input) { if (!partnerRows.some((row) => row.id === input.groupId && row.approved)) return fail("FORBIDDEN", "Only an approved Community Partner can request sponsorship."); if (!Number.isFinite(input.targetAmount) || input.targetAmount <= 0 || !input.title.trim() || !input.purpose.trim()) return fail("VALIDATION", "Campaign title, purpose, and positive target are required."); const id = `campaign-${Date.now()}`; campaignRows.push({ id, ...input, simulated: true }); return ok({ campaignId: id, simulated: true }); },
  async reportCampaignUse(input) { if (!campaignRows.some((row) => row.id === input.campaignId)) return fail("NOT_FOUND", "Campaign not found."); if (!input.note.trim() || !Number.isFinite(input.amount) || input.amount < 0) return fail("VALIDATION", "Add a use description and non-negative amount."); const id = `campaign-use-mock-${Date.now()}`; campaignUseRows.push({ id, campaignId: input.campaignId, amount: input.amount, note: input.note }); return ok({ updateId: id }); },
};

