import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/browser";
import { createSimulatedPledgeForCurrentUser } from "@/lib/services/neighbourhood-server";
import { logger } from "@/lib/observability/logger";
export const dynamic = 'force-static';
export async function GET() { const client = await createClient(); if (!client) return NextResponse.json({ ok: false, error: { code: "UNAVAILABLE", message: "Supabase is not configured." } }, { status: 503 }); const { data, error } = await client.from("sponsorship_campaigns").select("id,title,purpose,target_amount,activity,status,social_groups!inner(id,name,slug,description,approval_status)").eq("status", "active").eq("social_groups.approval_status", "approved").order("created_at", { ascending: false }).limit(100); return error ? NextResponse.json({ ok: false, error: { code: "UNAVAILABLE", message: "Campaigns are unavailable." } }, { status: 503 }) : NextResponse.json({ ok: true, data }); }
export async function POST(request: Request) { const requestId = request.headers.get("x-request-id") || crypto.randomUUID(); let body: unknown; try { body = await request.json(); } catch { return NextResponse.json({ ok: false, error: { code: "VALIDATION", message: "Invalid JSON request.", requestId } }, { status: 400 }); } const input = body as { campaignId?: string; amount?: number }; const result = await createSimulatedPledgeForCurrentUser({ campaignId: String(input.campaignId ?? ""), amount: Number(input.amount) }); if (!result.ok && !["VALIDATION", "FORBIDDEN", "NOT_FOUND"].includes(result.error.code)) logger.error("simulated pledge failed", { requestId, route: "/api/sponsorship", operation: "create_simulated_pledge", code: result.error.code }); return NextResponse.json(result, { status: result.ok ? 201 : result.error.code === "FORBIDDEN" ? 401 : result.error.code === "NOT_FOUND" ? 404 : result.error.code === "VALIDATION" ? 422 : 503, headers: { "x-request-id": requestId } }); }
export function generateStaticParams() {
  return [];
}