import Link from "next/link";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { saveIssueReview } from "./actions";
import { SectionHeading } from "@/components/admin/section-heading";
import { StatusBadge } from "@/components/admin/status-badge";

export default async function AdminIssues() {
  const client = await createClient();
  const { data, error } = client ? await client.from("admin_issue_review_queue").select("id,title,description,category,location,observed_at,review_status,urgent,verification_count,duplicate_of").in("review_status", ["unverified", "more_info", "accepted"]).order("urgent", { ascending: false }).order("created_at", { ascending: false }).limit(100) : { data: null, error: null };
  async function decide(formData: FormData) { "use server"; const result = await saveIssueReview({ issueId: String(formData.get("issueId")), action: String(formData.get("action")) as "accept" | "reject" | "refer" | "more_info" | "duplicate", reason: String(formData.get("reason")), canonicalIssueId: String(formData.get("canonicalIssueId") || "") }); if (!result.ok) throw new Error(result.error); revalidatePath("/admin/issues"); revalidatePath("/neighbourhood"); }
  return <section><SectionHeading eyebrow="Official review · persisted queue" title="Issue review" description="Community observation counts are separate from official decisions. Every action records an authorized reviewer and reason." />{!client && <p className="card" role="alert">Supabase is not configured; the review queue is unavailable.</p>}{error && <p className="card" role="alert">The review queue could not be loaded.</p>}{client && !error && !data?.length && <p className="card">No issues are awaiting review.</p>}<div style={{ display: "grid", gap: 14 }}>{(data ?? []).map((issue) => <article className="card" key={issue.id}><div style={{ display: "flex", justifyContent: "space-between", gap: 14, flexWrap: "wrap" }}><div><div className="eyebrow">{issue.category.replaceAll("_", " ")}</div><h2 style={{ marginBottom: 6 }}>{issue.title}</h2></div><div style={{ display: "flex", gap: 7 }}>{issue.urgent && <StatusBadge status="delayed" label="Urgent triage"/>}<StatusBadge status={issue.review_status} label={`Official: ${issue.review_status.replaceAll("_", " ")}`}/></div></div><p>{issue.description}</p><p style={{ color: "var(--muted)" }}>📍 {issue.location} · Observed {new Date(issue.observed_at).toLocaleString("en-IN")} · <strong>{issue.verification_count} community observations</strong></p><form action={decide} style={{ display: "grid", gap: 8 }}><input type="hidden" name="issueId" value={issue.id}/><label className="label">Decision reason<textarea className="field" name="reason" required minLength={3} rows={2} placeholder="Explain the official decision."/></label><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{(["accept", "more_info", "refer", "reject"] as const).map((action) => <button className="button secondary" name="action" value={action} key={action}>{action.replaceAll("_", " ")}</button>)}<Link className="button secondary" href={`/neighbourhood/issues/${issue.id}`}>Open public record</Link></div></form></article>)}</div></section>;
}
