import Link from "next/link";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { saveIssueReview } from "./actions";
import { SectionHeading } from "@/components/admin/section-heading";
import { StatusBadge } from "@/components/admin/status-badge";
import { EvidenceImage } from "@/components/admin/evidence-image";

export default async function AdminIssues() {
  const client = await createClient();
  const { data, error } = client ? await client.from("admin_issue_review_queue").select("id,title,description,category,location,observed_at,review_status,urgent,verification_count,duplicate_of").in("review_status", ["unverified", "more_info", "accepted"]).order("urgent", { ascending: false }).order("created_at", { ascending: false }).limit(100) : { data: null, error: null };
  const evidenceRows = client && data?.length ? await client.from("issues").select("id,evidence_path").in("id", data.map((issue) => issue.id)) : { data: [], error: null };
  const evidenceByIssue = new Map((evidenceRows.data ?? []).map((row) => [String(row.id), Boolean(row.evidence_path)]));
  const reviewItems = (data ?? []).map((issue) => ({ ...issue, has_evidence: evidenceByIssue.get(String(issue.id)) === true }));
  async function decide(formData: FormData) { "use server"; const result = await saveIssueReview({ issueId: String(formData.get("issueId")), action: String(formData.get("action")) as "accept" | "reject" | "refer" | "more_info" | "duplicate", reason: String(formData.get("reason")), canonicalIssueId: String(formData.get("canonicalIssueId") || "") }); if (!result.ok) throw new Error(result.error); revalidatePath("/admin/issues"); revalidatePath("/neighbourhood"); }
  return <section><SectionHeading eyebrow="Official review · persisted queue" title="Issue review" description="Community observation counts are separate from official decisions. Every action records an authorized reviewer and reason." />{!client && <p className="card" role="alert">Supabase is not configured; the review queue is unavailable.</p>}{error && <p className="card" role="alert">The review queue could not be loaded.</p>}{client && !error && !reviewItems.length && <p className="card">No issues are awaiting review.</p>}<div style={{ display: "grid", gap: 14 }}>{reviewItems.map((issue) => <article className="card" key={issue.id}><div style={{ display: "flex", justifyContent: "space-between", gap: 14, flexWrap: "wrap" }}><div><div className="eyebrow">{issue.category.replaceAll("_", " ")}</div><h2 style={{ marginBottom: 6 }}>{issue.title}</h2></div><div style={{ display: "flex", gap: 7 }}>{issue.urgent && <StatusBadge status="delayed" label="Urgent triage"/>}<StatusBadge status={issue.review_status} label={`Official: ${issue.review_status.replaceAll("_", " ")}`}/></div></div><p>{issue.description}</p><p style={{ color: "var(--muted)" }}>📍 {issue.location} · Observed {new Date(issue.observed_at).toLocaleString("en-IN")} · <strong>{issue.verification_count} community observations</strong></p>{issue.has_evidence ? <figure style={{ margin: "12px 0" }}><EvidenceImage src={`/api/admin/issues/${issue.id}/evidence`} alt={`Evidence for ${issue.title}`} /><figcaption style={{ color: "var(--muted)", fontSize: 13, marginTop: 6 }}>Private evidence preview. <a href={`/api/admin/issues/${issue.id}/evidence`} target="_blank" rel="noreferrer" style={{ textDecoration: "underline" }}>Open full size</a></figcaption></figure> : <p style={{ color: "var(--muted)" }}>No evidence attached.</p>}<form action={decide} style={{ display: "grid", gap: 8 }}><input type="hidden" name="issueId" value={issue.id}/><label className="label">Decision reason<textarea className="field" name="reason" required minLength={3} rows={2} placeholder="Explain the official decision."/></label><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{(["accept", "more_info", "refer", "reject"] as const).map((action) => <button className="button secondary" name="action" value={action} key={action}>{action === "accept" ? "Accept report" : action === "reject" ? "Reject report" : action.replaceAll("_", " ")}</button>)}<Link className="button secondary" href={`/admin/issues/${issue.id}`}>Open Admin review</Link></div></form></article>)}</div></section>;
}
