"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { createCoordinationCase, updateCoordinationCase } from "@/app/admin/coordination/actions";

export function CoordinationControls({ caseId }: { caseId?: string }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const result = await createCoordinationCase({ title: String(form.get("title")), projectIds: [String(form.get("projectId"))], segmentIds: [], reason: String(form.get("reason")) }); setBusy(false); setMessage(result.ok ? "Coordination case saved." : result.error); if (result.ok) router.refresh(); }
  async function update(operation: "proposal" | "accepted" | "rejected", form: HTMLFormElement) { if (!caseId) return; setBusy(true); const data = new FormData(form); const result = await updateCoordinationCase({ caseId, operation, reason: String(data.get("reason")), startDate: String(data.get("start") || ""), endDate: String(data.get("end") || "") }); setBusy(false); setMessage(result.ok ? "Coordination record updated." : result.error); if (result.ok) router.refresh(); }
  if (!caseId) return <NewCoordinationCase onSave={create} busy={busy} message={message}/>;
  return <form className="card" onSubmit={(event) => event.preventDefault()} style={{ display: "grid", gap: 8, marginTop: 12 }}><label className="label">Reason<textarea className="field" name="reason" required minLength={3}/></label><label className="label">Proposed start<input className="field" name="start" type="date"/></label><label className="label">Proposed end<input className="field" name="end" type="date"/></label><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button className="button secondary" disabled={busy} onClick={(e) => update("proposal", e.currentTarget.form!)}>Propose schedule</button><button className="button secondary" disabled={busy} onClick={(e) => update("accepted", e.currentTarget.form!)}>Accept</button><button className="button secondary" disabled={busy} onClick={(e) => update("rejected", e.currentTarget.form!)}>Reject</button></div>{message && <small role="status">{message}</small>}</form>;
}

function NewCoordinationCase({ onSave, busy, message }: { onSave: (event: FormEvent<HTMLFormElement>) => void; busy: boolean; message: string }) { const [projects, setProjects] = useState<Array<{id:string;title:string;location:string}>>([]); const [error, setError] = useState(""); useEffect(() => { fetch("/api/admin/projects").then((r)=>r.json()).then((r)=>{ if(r.ok) setProjects(r.data); else setError(r.error?.message ?? "Projects unavailable."); }).catch(()=>setError("Projects unavailable.")); }, []); return <form className="card" onSubmit={onSave} style={{ display: "grid", gap: 8, minWidth: 300 }}><strong>Open a coordination case</strong><label className="label">Title<input className="field" name="title" required minLength={3}/></label><label className="label">Project<select className="field" name="projectId" required defaultValue=""><option value="" disabled>Select a project</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.title} · {project.location}</option>)}</select></label><label className="label">Conflict reason<textarea className="field" name="reason" required minLength={3}/></label><button className="button" disabled={busy || projects.length===0}>{busy ? "Saving…" : "Create case"}</button>{(message||error)&&<small role="status">{message||error}</small>}</form>; }
