"use client";
import { useActionState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { requestPasswordReset, signIn, signOut, signUp, updatePassword, type AuthState } from "@/app/auth/actions";

const initial: AuthState = { ok: false, message: "" };
function Feedback({ state }: { state: AuthState }) { return state.message ? <p role={state.ok ? "status" : "alert"} style={{ color: state.ok ? "var(--green)" : "#a33", lineHeight: 1.5 }}>{state.message}</p> : null; }
export function SignInForm({ next = "/neighbourhood" }: { next?: string }) { const router = useRouter(); const [state, action, pending] = useActionState(signIn, initial); useEffect(() => { if (state.ok && state.redirectTo) router.replace(state.redirectTo); }, [state, router]); return <form action={action} noValidate><label className="label">Email<input className="field" type="email" name="email" required autoComplete="email" /></label><label className="label">Password<input className="field" type="password" name="password" required minLength={8} autoComplete="current-password" /></label><input type="hidden" name="next" value={next} /><button className="button" disabled={pending}>{pending ? "Signing in…" : "Sign in"}</button><Feedback state={state} /></form>; }
export function SignUpForm() { const router = useRouter(); const [state, action, pending] = useActionState(signUp, initial); useEffect(() => { if (state.ok && state.redirectTo) router.replace(state.redirectTo); }, [state, router]); return <form action={action} noValidate><label className="label">Display name<input className="field" name="displayName" required minLength={2} maxLength={80} autoComplete="name" /></label><label className="label">Email<input className="field" type="email" name="email" required autoComplete="email" /></label><label className="label">Password<input className="field" type="password" name="password" required minLength={8} autoComplete="new-password" /></label><button className="button" disabled={pending}>{pending ? "Creating account…" : "Create account"}</button><Feedback state={state} /></form>; }
export function ForgotPasswordForm() { const [state, action, pending] = useActionState(requestPasswordReset, initial); return <form action={action} noValidate><label className="label">Email<input className="field" type="email" name="email" required autoComplete="email" /></label><button className="button" disabled={pending}>{pending ? "Requesting…" : "Send reset email"}</button><Feedback state={state} /></form>; }
export function ResetPasswordForm() { const router = useRouter(); const [state, action, pending] = useActionState(updatePassword, initial); useEffect(() => { if (state.ok && state.redirectTo) router.replace(state.redirectTo); }, [state, router]); return <form action={action} noValidate><label className="label">New password<input className="field" type="password" name="password" required minLength={8} autoComplete="new-password" /></label><label className="label">Confirm password<input className="field" type="password" name="confirmation" required minLength={8} autoComplete="new-password" /></label><button className="button" disabled={pending}>{pending ? "Updating…" : "Update password"}</button><Feedback state={state} /></form>; }
export function SignOutButton() { const router = useRouter(); const [state, action, pending] = useActionState(signOut, initial); useEffect(() => { if (state.ok && state.redirectTo) router.replace(state.redirectTo); }, [state, router]); return <form action={action}><button className="navlink" disabled={pending}>{pending ? "Signing out…" : "Sign out"}</button><Feedback state={state} /></form>; }
