create extension if not exists pgcrypto;
create extension if not exists postgis;
create type public.app_role as enum ('admin','common','group');
create type public.project_status as enum ('planned','active','delayed','completed','cancelled');
create type public.issue_review_status as enum ('unverified','accepted','rejected','referred','more_info','duplicate');
create type public.issue_source as enum ('citizen','external','detector');
create type public.group_approval_status as enum ('pending','approved','rejected','suspended');
create type public.group_task_status as enum ('adopted','in_progress','awaiting_confirmation','confirmed','disputed','reopened','referred');
create type public.confirmation_status as enum ('confirmed','disputed');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, display_name text not null, primary_role public.app_role not null default 'common', created_at timestamptz not null default now());
create table public.admin_scopes(id uuid primary key default gen_random_uuid(), admin_id uuid not null references public.profiles(id) on delete cascade, department text, area text, unique(admin_id,department,area));
create table public.social_groups(id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id), name text not null, slug text not null unique, description text not null default '', approval_status public.group_approval_status not null default 'pending', location text not null, service_area text not null, contact_email text, eligible_work text[] not null default '{}', created_at timestamptz not null default now());
create table public.group_members(group_id uuid not null references public.social_groups(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, permission text not null check(permission in ('owner','editor','viewer')), created_at timestamptz not null default now(), primary key(group_id,user_id));
create table public.street_segments(id uuid primary key default gen_random_uuid(), name text not null, area text, geom geography(linestring,4326), created_at timestamptz not null default now());
create table public.projects(id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null, description text not null, work_type text, department text not null, contractor text, location text not null, geom geography(point,4326), planned_start date not null, original_expected_end date not null, expected_end date not null, status public.project_status not null default 'planned', budget numeric(14,2) check(budget is null or budget>=0), funding_source text, is_published boolean not null default false, created_by uuid references public.profiles(id), updated_at timestamptz not null default now(), check(expected_end>=planned_start));
create table public.project_segments(project_id uuid not null references public.projects(id) on delete cascade, segment_id uuid not null references public.street_segments(id), primary key(project_id,segment_id));
create table public.project_events(id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, actor_id uuid references public.profiles(id), event_type text not null, details jsonb not null default '{}', public_visible boolean not null default true, created_at timestamptz not null default now());
create table public.coordination_cases(id uuid primary key default gen_random_uuid(), title text not null, project_ids uuid[] not null, segment_ids uuid[] not null default '{}', conflict_reason text not null, decision text, decision_reason text, proposed_schedule jsonb, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.issues(id uuid primary key default gen_random_uuid(), title text not null, description text not null, category text not null, location text not null, geom geography(point,4326) not null, observed_at timestamptz not null, source public.issue_source not null default 'citizen', external_source text, external_id text, source_observed_at timestamptz, evidence_path text, public_evidence_path text, reporter_id uuid references public.profiles(id), review_status public.issue_review_status not null default 'unverified', urgent boolean not null default false, canonical_issue_id uuid references public.issues(id), created_at timestamptz not null default now());
create table public.issue_verifications(issue_id uuid not null references public.issues(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, personally_observed boolean not null check(personally_observed), created_at timestamptz not null default now(), primary key(issue_id,user_id));
create table public.issue_project_matches(id uuid primary key default gen_random_uuid(), issue_id uuid not null references public.issues(id) on delete cascade, project_id uuid not null references public.projects(id) on delete cascade, status text not null default 'suggested' check(status in ('suggested','approved','rejected')), reason text, reviewed_by uuid references public.profiles(id), created_at timestamptz not null default now(), unique(issue_id,project_id));
create table public.official_reviews(id uuid primary key default gen_random_uuid(), issue_id uuid not null references public.issues(id), admin_id uuid not null references public.profiles(id), action text not null check(action in ('accept','reject','refer','more_info','duplicate','response','flag_review')), reason text not null, public_response text, referred_department text, canonical_issue_id uuid references public.issues(id), created_at timestamptz not null default now());
create table public.group_tasks(id uuid primary key default gen_random_uuid(), issue_id uuid not null references public.issues(id), group_id uuid not null references public.social_groups(id), status public.group_task_status not null default 'adopted', accepted_by uuid references public.profiles(id), completion_evidence_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(issue_id,group_id));
create table public.group_task_events(id uuid primary key default gen_random_uuid(), task_id uuid not null references public.group_tasks(id) on delete cascade, actor_id uuid references public.profiles(id), event_type text not null, note text, evidence_path text, created_at timestamptz not null default now());
create table public.group_task_confirmations(task_id uuid not null references public.group_tasks(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, status public.confirmation_status not null, note text, created_at timestamptz not null default now(), primary key(task_id,user_id));
create table public.sponsorship_campaigns(id uuid primary key default gen_random_uuid(), group_id uuid not null references public.social_groups(id), activity text, title text not null, purpose text not null, target_amount numeric(12,2) not null check(target_amount>0), status text not null default 'active' check(status in ('active','cancelled','completed')), created_at timestamptz not null default now());
create table public.sponsorship_pledges(id uuid primary key default gen_random_uuid(), campaign_id uuid not null references public.sponsorship_campaigns(id), sponsor_id uuid references public.profiles(id), sponsor_label text, amount numeric(12,2) not null check(amount>0), simulated boolean not null default true check(simulated), created_at timestamptz not null default now());
create table public.project_follows(project_id uuid not null references public.projects(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), primary key(project_id,user_id));
create index projects_geom_idx on public.projects using gist(geom);
create index issues_geom_idx on public.issues using gist(geom);
create index street_segments_geom_idx on public.street_segments using gist(geom);
create index projects_status_dates_idx on public.projects(status,expected_end);
create index issues_review_recent_idx on public.issues(review_status,created_at desc);
create index issues_category_recent_idx on public.issues(category,created_at desc);
create index group_tasks_status_idx on public.group_tasks(status,updated_at desc);
create index project_events_history_idx on public.project_events(project_id,created_at desc);

create or replace function public.current_role() returns public.app_role language sql stable security definer set search_path=public as $$ select primary_role from public.profiles where id=auth.uid() $$;
create or replace function public.is_approved_group_member(target_group uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.group_members gm join public.social_groups g on g.id=gm.group_id where gm.group_id=target_group and gm.user_id=auth.uid() and g.approval_status='approved') $$;
alter table public.profiles enable row level security;
alter table public.admin_scopes enable row level security;
alter table public.social_groups enable row level security;
alter table public.group_members enable row level security;
alter table public.street_segments enable row level security;
alter table public.projects enable row level security;
alter table public.project_segments enable row level security;
alter table public.project_events enable row level security;
alter table public.coordination_cases enable row level security;
alter table public.issues enable row level security;
alter table public.issue_verifications enable row level security;
alter table public.issue_project_matches enable row level security;
alter table public.official_reviews enable row level security;
alter table public.group_tasks enable row level security;
alter table public.group_task_events enable row level security;
alter table public.group_task_confirmations enable row level security;
alter table public.sponsorship_campaigns enable row level security;
alter table public.sponsorship_pledges enable row level security;
alter table public.project_follows enable row level security;
create policy "profiles read self" on public.profiles for select using(id=auth.uid());
create policy "profiles insert self as common" on public.profiles for insert with check(id=auth.uid() and primary_role='common');
create policy "profiles update self" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid() and primary_role='common');
create policy "admin scopes self" on public.admin_scopes for select using(admin_id=auth.uid());
create policy "public approved groups" on public.social_groups for select using(approval_status='approved');
create policy "group owner reads own profile" on public.social_groups for select using(owner_id=auth.uid());
create policy "group owner applies" on public.social_groups for insert with check(owner_id=auth.uid() and public.current_role()='common' and approval_status='pending');
create policy "approved group editors update" on public.social_groups for update using(public.is_approved_group_member(id)) with check(public.is_approved_group_member(id));
create policy "group member reads membership" on public.group_members for select using(user_id=auth.uid() or public.is_approved_group_member(group_id));
create policy "public published projects" on public.projects for select using(is_published);
create policy "public segments" on public.street_segments for select using(true);
create policy "public project segments" on public.project_segments for select using(exists(select 1 from public.projects p where p.id=project_id and p.is_published));
create policy "public project events" on public.project_events for select using(public_visible and exists(select 1 from public.projects p where p.id=project_id and p.is_published));
create policy "public reports" on public.issues for select using(true);
create policy "signed in submits report" on public.issues for insert with check(auth.uid() is not null and (reporter_id is null or reporter_id=auth.uid()) and review_status='unverified' and urgent=false);
create policy "verification counts visible" on public.issue_verifications for select using(true);
create policy "one personal verification" on public.issue_verifications for insert with check(auth.uid()=user_id and personally_observed and public.current_role()='common');
create policy "own verification delete" on public.issue_verifications for delete using(auth.uid()=user_id);
create policy "public reviewed project match" on public.issue_project_matches for select using(status='approved');
create policy "public group tasks" on public.group_tasks for select using(exists(select 1 from public.social_groups g where g.id=group_id and g.approval_status='approved'));
create policy "approved group accepts task" on public.group_tasks for insert with check(public.is_approved_group_member(group_id) and accepted_by=auth.uid() and status='adopted');
create policy "approved group updates own task" on public.group_tasks for update using(public.is_approved_group_member(group_id)) with check(public.is_approved_group_member(group_id));
create policy "public group task history" on public.group_task_events for select using(exists(select 1 from public.group_tasks t join public.social_groups g on g.id=t.group_id where t.id=task_id and g.approval_status='approved'));
create policy "group records task event" on public.group_task_events for insert with check(actor_id=auth.uid() and exists(select 1 from public.group_tasks t where t.id=task_id and public.is_approved_group_member(t.group_id)));
create policy "community confirmations public" on public.group_task_confirmations for select using(true);
create policy "common people confirm independent work" on public.group_task_confirmations for insert with check(auth.uid()=user_id and public.current_role()='common' and exists(select 1 from public.group_tasks t join public.social_groups g on g.id=t.group_id where t.id=task_id and t.status='awaiting_confirmation' and g.owner_id<>auth.uid() and not exists(select 1 from public.group_members gm where gm.group_id=g.id and gm.user_id=auth.uid())));
create policy "public active campaigns" on public.sponsorship_campaigns for select using(status='active' and exists(select 1 from public.social_groups g where g.id=group_id and g.approval_status='approved'));
create policy "group manages campaigns" on public.sponsorship_campaigns for all using(public.is_approved_group_member(group_id)) with check(public.is_approved_group_member(group_id));
create policy "simulated pledges visible" on public.sponsorship_pledges for select using(true);
create policy "common people simulated pledges" on public.sponsorship_pledges for insert with check(simulated and (sponsor_id is null or sponsor_id=auth.uid()));
create policy "own follows" on public.project_follows for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "admin review rows private" on public.official_reviews for select using(public.current_role()='admin');
create policy "admin coordinates" on public.coordination_cases for select using(public.current_role()='admin');
create policy "admin scoped read published projects" on public.projects for select using(public.current_role()='admin');

